# Generated by Django 5.0.2 on 2024-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone_num", models.PositiveIntegerField(max_length=1)),
                ("password", models.CharField(max_length=20)),
                ("is_customer", models.BooleanField(max_length=1)),
            ],
        ),
    ]
