# Generated by Django 5.0.2 on 2024-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_num",
            field=models.PositiveIntegerField(),
        ),
    ]
