# Generated by Django 5.0.2 on 2024-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_user_phone_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("details", models.CharField(max_length=1000)),
                ("truth", models.BooleanField(max_length=1)),
                ("rating", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
