# Generated by Django 5.0.2 on 2024-03-27 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_quality_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quality",
            new_name="Service",
        ),
    ]
